package models

type Player struct {
	Class               string `json:"class"`
	GlBrkSavePct        string `json:"glbrksavepct"`
	GlBrkSaves          string `json:"glbrksaves"`
	GlBrkShots          string `json:"glbrkshots"`
	GlD_saves           string `json:"gldsaves"`
	GlGa                string `json:"glga"`
	GlGaa               string `json:"glgaa"`
	GlPenSavePct        string `json:"glpensavepct"`
	GlPenSaves          string `json:"glpensaves"`
	GlPenShots          string `json:"glpenshots"`
	GlPkClearZone       string `json:"glpkclearzone"`
	GlPokeChecks        string `json:"glpokechecks"`
	GlSavePct           string `json:"glsavepct"`
	GlSaves             string `json:"glsaves"`
	GlShots             string `json:"glshots"`
	GlSOperiods         string `json:"glsoperiods"`
	IsGuest             string `json:"isGuest"`
	MemberString        string `json:"memberString"`
	OpponentClubID      string `json:"opponentClubId"`
	OpponentScore       string `json:"opponentScore"`
	OpponentTeamArtAbbr string `json:"opponentTeamArtAbbr"`
	OpponentTeamID      string `json:"opponentTeamId"`
	PlayerDNF           string `json:"player_dnf"`
	PlayerLevel         string `json:"playerLevel"`
	PNhlOnlineGameType  string `json:"pNhlOnlineGameType"`
	Position            string `json:"position"`
	PosSorted           string `json:"posSorted"`
	RankPoints          string `json:"rankpoints"`
	RankTierAssetID     string `json:"ranktierassetid"`
	RatingDefense       string `json:"ratingDefense"`
	RatingOffense       string `json:"ratingOffense"`
	RatingTeamplay      string `json:"ratingTeamplay"`
	RemovedReason       string `json:"removedReason"`
	Result              string `json:"result"`
	Score               string `json:"score"`
	ScoreRaw            string `json:"scoreRaw"`
	ScoreString         string `json:"scoreString"`
	SkAssists           string `json:"skassists"`
	SkBs                string `json:"skbs"`
	SkDeflections       string `json:"skdeflections"`
	SkFOL               string `json:"skfol"`
	SkFOPct             string `json:"skfopct"`
	SkFOW               string `json:"skfow"`
	SkGiveaways         string `json:"skgiveaways"`
	SkGoals             string `json:"skgoals"`
	SkGWG               string `json:"skgwg"`
	SkHits              string `json:"skhits"`
	SkInterceptions     string `json:"skinterceptions"`
	SkPassAttempts      string `json:"skpassattempts"`
	SkPasses            string `json:"skpasses"`
	SkPassPct           string `json:"skpasspct"`
	SkPenaltiesDrawn    string `json:"skpenaltiesdrawn"`
	SkPIM               string `json:"skpim"`
	SkPKClearZone       string `json:"skpkclearzone"`
	SkPlusMin           string `json:"skplusmin"`
	SkPossession        string `json:"skpossession"`
	SkPPG               string `json:"skppg"`
	SkSaucerPasses      string `json:"sksaucerpasses"`
	SkSHG               string `json:"skshg"`
	SkShotAttempts      string `json:"skshotattempts"`
	SkShotOnNetPct      string `json:"skshotonnetpct"`
	SkShotPct           string `json:"skshotpct"`
	SkShots             string `json:"skshots"`
	SkTakeaways         string `json:"sktakeaways"`
	TeamArtAbbr         string `json:"teamArtAbbr"`
	TeamID              string `json:"teamId"`
	TeamSide            string `json:"teamSide"`
	Toi                 string `json:"toi"`
	ToiSeconds          string `json:"toiseconds"`
	PlayerName          string `json:"playername"`
	ClientPlatform      string `json:"clientPlatform"`
}
